### ISSUE TITLE
hl7.client is not visible

### ISSUE THREAD

**Issue by akantak** [johnpaulett/python-hl7#19]
It is mention about hl7.client.MLLPClient in API docs, but it is impossible to import hl7.client when installed using pip. You omit client section in \_\_init\_\_.py file.
Adding `from .client import MLLPClient` should fix the problem.

**Comment by johnpaulett** [comment]
The documentation references the full path to the class, it seems to work just fine if you do `from hl7.client import MLLPClient`.  Are you receiving errors doing that?

**Comment by johnpaulett** [comment]
Great.  I think we avoided importing client.py from the __init__.py, since the client.py drags in other network-related dependencies that are not necessary for pure-parsing usage.  Glad we could get it working for you.
