### ISSUE TITLE
assertionError

### ISSUE THREAD

**Issue by rafiks** [johnpaulett/python-hl7#20]
hi!
i am getting an assertion Error when i create a python script. Using Jupyter seems to work.
i have python 3.7.3 interpreter. Ipython 7.4.0
platform: Windows 10

i am still learning python.
not sure if there is something wrong with my code or is it something else.

```
import hl7
f_open = open("message")
hlmessage = f_open.read()
myhl7 = hl7.parse("hlmessage")
```
my hl7 message which i wrote to  file.

MSH|^~\&|EPIC|EPICADT|SMS|SMSADT|199912271408|CHARRIS|ADT^A04|1817457|D|2.5|
PID||0493575^^^2^ID 1|454721||DOE^JOHN^^^^|DOE^JOHN^^^^|19480203|M||B|254 MYSTREET AVE^^MYTOWN^OH^44123^USA||(216)123-4567|||M|NON|400003403~1129086|
NK1||ROE^MARIE^^^^|SPO||(216)123-4567||EC|||||||||||||||||||||||||||
PV1||O|168 ~219~C~PMA^^^^^^^^^||||277^ALLEN MYLASTNAME^BONNIE^^^^|||||||||| ||2688684|||||||||||||||||||||||||199912271408||||||002376853

**Comment by rafiks** [comment]
error message:
Traceback (most recent call last):
  File "myhl7.py", line 6, in <module>
    myhl7 = hl7.parse("hlmessage")
  File "C:\Users\rab94d\AppData\Local\Programs\Python\Python37\lib\site-packages\hl7\parser.py", line 45, in parse
    plan = create_parse_plan(strmsg, factory)
  File "C:\Users\rab94d\AppData\Local\Programs\Python\Python37\lib\site-packages\hl7\parser.py", line 88, in create_parse_plan
    assert strmsg[:3] in ('MSH')
AssertionError

**Comment by johnpaulett** [comment]
Should be `hl7.parse(hlmessage)` -- You're trying to parse the string `"hlmessage"`, not the variable `hlmessage`
