### ISSUE TITLE
I am having problems with component separators 

### ISSUE THREAD

**Issue by tiagoataquila** [johnpaulett/python-hl7#46]
Hello.

I am facing some issues with component separators using the library (I was used to  using a proprietary implementation  before so I am net at python-hl7)
something simple as  a message from:

```
message = 'MSH|^~\&|\r'
message += 'PID|Field1|Component1^Component2|Component1^SubComponent1&SubComponent2^Component3|Repeat1~Repeat2\r'
```
send that trough mllp and receive it with this library:

By what I understood from the docs, I could  access  my_message['PID'][2][1]  to Access Component1.  But that fails in 2 ways. First my_message['PID'] returns a length 1"list" so I have to access my_message['PID'] [0][2].  The same happend for the next level I have to access it as my_message['PID'][0][2][0][1]

Sorry if this is not a bug, but by what I understood from the documentation that is not the expected behavior:

A sample that I reproduce this would be:

```
message = 'MSH|^~\&|\r'
message += 'PID|Field1|Component1^Component2|Component1^Sub-Component1&Sub-Component2^Component3|Repeat1~Repeat2\r'

hl7_message = hl7.parse(message)
```
If I read hl7_message['PID'][2] here it already crashes...
I need to read as hl7_message['PID'][0][2]

Did I missunderstand completely the docs or is there something really wrong?

**Comment by johnpaulett** [comment]
See [the docs](https://python-hl7.readthedocs.io/en/latest/index.html#:~:text=Since%20many%20many%20types%20of%20segments%20only%20have%20a%20single%20instance%20in%20a%20message):

> Since many many types of segments only have a single instance in a message (e.g. PID or MSH), [hl7.Message.segment()](https://python-hl7.readthedocs.io/en/latest/api.html#hl7.Message.segment) provides a convienance wrapper around [hl7.Message.segments()](https://python-hl7.readthedocs.io/en/latest/api.html#hl7.Message.segments) that returns the first matching [hl7.Segment](https://python-hl7.readthedocs.io/en/latest/api.html#hl7.Segment):
```
>>> h.segment('PID')[3][0]
'555-44-4444'
>>> h.segment('PID')[3][0] is h.segment('PID')(3)(1)
True
```

E.g. for OBX segments, there are likely multiple thus the h['OBX'] list allows access to each one.  In the PID case, there is a single, so you can use `.segments('PID')`.  The library contains no deep knowledge about what is legal in the spec, only trying to provide a consistent interface to access.
