### ISSUE TITLE
Assertion errors when I try to save message to a textField in Django

### ISSUE THREAD

**Issue by id2359** [johnpaulett/python-hl7#58]
Question (  not saying this is a bug in python-hl7)
Something has changed ( we use 0.4.5) potentially in the messages we're seeing from an external source.

Previously I was assigning the message ok like so:

django_model.content = message ( a hl7.Message)

django_model.save()

But I'm seeing assertion errors -  what could cause assertion errors in trying to write a message object to a string.

The message object has been constructed / inited already and a couple of fields parsed out ok.

**Comment by johnpaulett** [comment]
The `message` is not a `str`, so it probably needs to be converted first `str(message)`.  

This does not sound like an issue in this library, so closing. Feel free to reopen with specific details and research if you find it is

**Comment by id2359** [comment]
It's an orm it will be calling str or a string representation - this was working in 0.4.2 - I think we've noticed these errors since bumping to 0.4.5.

**Comment by johnpaulett** [comment]
Yep, I am familiar with the Django ORM.  What I'm suggesting is you were expecting an **implicit** conversion from an object to a str.  I'm suggesting to make that an **explicit** conversion by calling `str(message)`.  

If `str(message)` does not return a str, then we have a bug in python-hl7 that we'd address.  

If you still have issues and want assistance, I'd suggest a minimal example of the model definition, the code to reproduce, and the stack trace that you encounter.
